### ISSUE TITLE
TestData command does not log to db table [usd_AppliedDatabaseTestDataScript]

### ISSUE THREAD

**Issue by chiragdani** [ClearMeasure/AliaSQL#16]
When we execute TestData command, it runs scripts of TestData folder fine. However, it is not logging into database table: [usd_AppliedDatabaseTestDataScript].
This functionality was working fine for AliaSQL.exe v1.4.0.1208

**Comment by ericdc1** [comment]
Confirmed. Seems I accepted a bad pull request. I am looking into this now.

**Comment by ericdc1** [comment]
Fixed in 1.4.2. It is published here and on Nuget. I added a unit test for this case. Thanks for reporting.
